import {
  transferERC20FromMaticToEthereumUsingPOSBridge,
  transferERC20FromEthereumToMaticUsingPOSBridge,
  transferETHFromEthereumToMaticUsingPOSBridge,
  transferERC721FromEthereumToMaticUsingPOSBridge,
  transferERC721FromMaticToEthereumUsingPOSBridge,
  transferERC1155FromEthereumToMaticUsingPOSBridge,
  transferERC1155FromMaticToEthereumUsingPOSBridge,
} from "./bridges";

export {
  transferERC20FromMaticToEthereumUsingPOSBridge,
  transferERC20FromEthereumToMaticUsingPOSBridge,
  transferETHFromEthereumToMaticUsingPOSBridge,
  transferERC721FromEthereumToMaticUsingPOSBridge,
  transferERC721FromMaticToEthereumUsingPOSBridge,
  transferERC1155FromEthereumToMaticUsingPOSBridge,
  transferERC1155FromMaticToEthereumUsingPOSBridge,
};
